# version: '3.9'
services:
  # start-front:
  #     image: alpine
  #     depends_on:
  #       - backend
  #       - frontend
  #     command: sh -c "echo 'Back service started. Now running Front service.' && sleep 5 && docker-compose run --rm frontend"

  backend:
    container_name: manja-backend-container
    image:
      node:21-alpine
    working_dir: /app
    volumes:
      - type: bind
        source: ./manja-backend
        target: /app
    expose:
      - 5000
    ports: 
      - 5000:5000
    user: "1000"
    # build: ./manja-backend
    # restart: no
    # detach: true
    tty: true

  # frontend:
  #   container_name: salon-front-container
  #   user: "1000:1000"
  #   environment:
  #     - UID=1000  # Set the desired user ID here
  #   build: ./front
  #   image: salon-front-image
  #   volumes:
  #     - ./front:/app
  #   ports: 
  #     - 4200:4200
  #   restart: no
  #   # detach: true
  #   tty: true


  db:
    container_name: manja-db-container
    image: mongo
    working_dir: /app
    volumes:
      - mongo_data_volume:/app/data/db
    expose:
      - 27017
    ports: 
        - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myadmin
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

volumes:
  mongo_data_volume:
