# version: '3.9'
services:
  # start-front:
  #     image: alpine
  #     depends_on:
  #       - backend
  #       - frontend
  #     command: sh -c "echo 'Back service started. Now running Front service.' && sleep 5 && docker-compose run --rm frontend"

  backend:
    container_name: salon-back-container
    user: "1000"
    # environment:
    #   - UID=1000  # Set the desired user ID here
    build: ./back
    image: salon-back-image
    volumes:
      - type: bind
        source: ./back
        target: /app
    
    ports: 
      - "5000:5000"
    # restart: no
    # detach: true
    tty: true
    # command: docker

  # frontend:
  #   container_name: salon-front-container
  #   user: "1000:1000"
  #   environment:
  #     - UID=1000  # Set the desired user ID here
  #   build: ./front
  #   image: salon-front-image
  #   volumes:
  #     - ./front:/app
  #   ports: 
  #     - 4200:4200
  #   restart: no
  #   # detach: true
  #   tty: true
